# Generated by Django 4.1.5 on 2023-01-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_bookings_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='no_of_persons',
            field=models.IntegerField(),
        ),
    ]
