# Generated by Django 4.1.5 on 2023-01-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_alter_bookings_no_of_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
